project:
  type: website
  output-dir: docs

lang: es

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    css: resources/styles/galeria.css
    other-links:
      - text: "Repositorio de código fuente"
        href: "https://github.com/LezahA/debconf26"
        icon: github

execute:
  echo: false